#bcm_hal_cam-objs := hal_cam.o
bcm_hal_cam_still_YUV-objs := cam_cntrl_2153.o hal_cam.o hal_cam_CMI_YUVdrv.o
#obj-$(CONFIG_BRCM_HAL_CAM) += bcm_hal_cam.o
obj-$(CONFIG_BRCM_HAL_CAM_WITH_STILL_YUV) += bcm_hal_cam_still_YUV.o
obj-$(CONFIG_BCM_CAM_TCM9001MD) += camdrv_tcm9001.o  hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_MT9T111) += camdrv_mt9t111_yuv.o  hal_cam_core_ath_dual.o
#obj-$(CONFIG_BCM_CAM_OV5640) += camdrv_ov5640.o hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_STV0986) += camdrv_stv0986.o hal_cam_CMI_drv.o cam_cntrl_2153.o
obj-$(CONFIG_BCM_CAM_OV2655) += camdrv_ov2655.o
obj-$(CONFIG_BCM_CAM_STV0987) += camdrv_stv0987.o hal_cam_core_ath.o
obj-$(CONFIG_BCM_CAM_MT9D115) += camdrv_mt9D115.o hal_cam_core_ath.o
#hanwei@wind-mobi.com 2011.10.20
obj-$(CONFIG_BCM_CAM_OV7692) += camdrv_ov7692.o  hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_HI253) += camdrv_hi253_yuv.o  hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_S5K5CA) += camdrv_s5k5ca.o  hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_OV7690) += camdrv_ovm7690.o  hal_cam_core_ath_dual.o
obj-$(CONFIG_BCM_CAM_OV5640) += camdrv_ov5640_Org.o  hal_cam_core_ath_dual.o
